const colors = {
  LightBrownBackground: "#F9F2E6",
  LightBrownDropShadow: "#E4D1BC",
  DarkBrownBackground: "#F3C68E",
  DarkBrownDropShadow: "#C9A373",
  PrimaryPurpleBackground: "#BF8EFF",
  PrimaryPurpleDropShadow: "#A57CDA",
  PrimaryGrayBackground: "#F3F4F6",
  PrimaryGrayDropShadow: "#D9D9D9",
  PrimaryWhite: "#FFFFFF",
  BrownPrimaryText: "#956E60",
  DarkPrimaryText: "#4B5563",
  GrayText: "#B5B5B5",
  Disabled: "#959595",
  DisabledBacking: "#7D7E79",
  DisabledText: "#C8C9C4",
  DarkPurpleBackground: "#1E1F33",
  DarkPurpleButton: "#2C2E4B",
  DarkPurpleButtonDropShadow: "#001123",
  PrimaryBlue: "#68AFFF",
  EmojiGrayBackground: "#F0F0F0",
  PrimaryGreenBackground: "#51B778",
  PrimaryGreenDropShadow: "#3C8F5C",
  DarkSecondaryText: "#282828",
  GoalCreatedBackground: "#9CC1F5",
  PrimarySecondaryPurpleDropShadow: "#8187F5",
  IdeasPrimaryColor: "#0B466E",
  IdeasPrimaryBackground: "#EEF5FB",
  SolaraGreen: "#40CAA0",
  SolaraGreenDropShadow: "#4AA78B",
  GabrielBackground: "#A0B57A",
  GabrielGoalBackground: "#7EA159",
  GabrielGoalDropShadow: "#517D5A",
  ZoneOneBattleBackground: "#505900",
  ZoneOneBattleText: "#D4D20E",
} as const;

export type Colors = typeof colors; // Extract the type for the colors object
export default colors;
