import { StyleSheet } from "react-native";
import colors from "@/constants/colors";

export const styles = StyleSheet.create({
  container: {
    backgroundColor: colors.GoalCreatedBackground,
    flex: 1,
    paddingTop: "30%",
  },
  topContainer: {
    flex: 0.65,
    paddingHorizontal: "5%",
    alignItems: "center",
    justifyContent: "center",
  },
  contentContainer: {
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  overlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)", // Black tint with some transparency
    zIndex: 1,
  },
  menu: {
    position: "absolute",
    bottom: 0,
    width: "100%",
    height: "75%",
    backgroundColor: colors.GoalCreatedBackground,
    paddingHorizontal: 20,
    paddingVertical: 30,
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    zIndex: 2,
    alignItems: "center",
  },
  imageBackground: {
    flex: 0.35,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  character: {
    position: "absolute",
    bottom: 20,
    height: "70%",
    transform: [{ translateX: "4%" }],
  },
  actionContainer: {
    width: "100%",
    paddingHorizontal: 23,
    paddingVertical: 14,
    borderRadius: 10,
    backgroundColor: colors.PrimarySecondaryPurpleDropShadow,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginVertical: 6,
    borderColor: colors.PrimaryWhite,
    borderWidth: 2,
  },
  actionRowContainer: {
    width: "100%",
    paddingHorizontal: 23,
    paddingVertical: 14,
    backgroundColor: colors.PrimarySecondaryPurpleDropShadow,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderColor: colors.PrimaryWhite,
    borderBottomWidth: 2,
  },
  multipleActionContainer: {
    width: "100%",
    borderRadius: 10,
    backgroundColor: colors.PrimarySecondaryPurpleDropShadow,
    marginVertical: 6,
    borderColor: colors.PrimaryWhite,
    borderWidth: 2,
    padding: 0,
    overflow: "hidden",
  },
  menuContent: {
    width: "100%",
  },
  selectedRow: {
    backgroundColor: "rgba(255, 255, 255, 0.1)",
  },
  timeOptionsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  timeOption: {
    paddingVertical: 15,
    paddingHorizontal: 15,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.PrimaryWhite,
    marginBottom: 12,
    width: "48%",
    alignItems: "center",
    backgroundColor: colors.PrimarySecondaryPurpleDropShadow,
  },
  selectedTimeOption: {
    backgroundColor: colors.PrimaryPurpleBackground,
    borderColor: colors.PrimaryWhite,
    borderWidth: 2,
  },
  doneButton: {
    backgroundColor: colors.PrimaryPurpleBackground,
    paddingVertical: 15,
    borderRadius: 10,
    alignItems: "center",
    marginTop: 15,
    borderWidth: 1,
    borderColor: colors.PrimaryWhite,
    width: "100%",
  },
  scrollContainer: {
    width: "100%",
    maxHeight: "90%",
  },
  scrollContentContainer: {
    paddingBottom: 20,
  },
  explanationText: {
    marginBottom: 15,
    lineHeight: 20,
    opacity: 0.9,
  },
  optionText: {
    fontWeight: "600",
    textShadowColor: "rgba(0, 0, 0, 0.2)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  optionContentContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
  },
  checkIcon: {
    marginLeft: 10,
  },
});
