import { Dimensions, StyleSheet } from "react-native";
const { width, height } = Dimensions.get("window");

export const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContainer: {
    width: width * 0.88,
    maxHeight: height * 0.85,
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    overflow: "hidden",
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.2)",
    elevation: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
  },
  backgroundGradient: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 140,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    overflow: "hidden",
  },
  characterImage: {
    position: "absolute",
    top: 15,
    right: 20,
    width: 110,
    height: 110,
    borderRadius: 55,
    borderWidth: 3,
    borderColor: "#FFFFFF",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 5,
    elevation: 8,
  },
  headerSection: {
    width: "100%",
    paddingTop: 30,
    paddingBottom: 15,
    alignItems: "center",
    flexDirection: "row",
    paddingHorizontal: 25,
    justifyContent: "space-between",
  },
  titleContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.15)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 18,
  },
  trophyIcon: {
    marginRight: 8,
  },
  titleText: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#FFFFFF",
    textShadowColor: "rgba(0, 0, 0, 0.3)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
  },
  xpBadge: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 6,
    flexDirection: "row",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 5,
  },
  xpText: {
    fontSize: 15,
    fontWeight: "bold",
    marginLeft: 5,
  },
  contentContainer: {
    width: "100%",
    paddingHorizontal: 22,
    paddingTop: 55,
    paddingBottom: 25,
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    marginTop: -35,
  },
  rewardsSection: {
    marginTop: 10,
    paddingBottom: 20,
  },
  sectionTitle: {
    fontSize: 19,
    fontWeight: "700",
    color: "#222222",
    marginBottom: 18,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  rewardsGrid: {
    flexDirection: "row",
    justifyContent: "space-between",
    flexWrap: "wrap",
  },
  rewardCard: {
    backgroundColor: "#F9F9F9",
    borderRadius: 18,
    padding: 16,
    width: "48%",
    alignItems: "center",
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#EEEEEE",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  rewardIconContainer: {
    width: 52,
    height: 52,
    borderRadius: 26,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 4,
  },
  rewardAmount: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#222222",
  },
  rewardType: {
    fontSize: 14,
    color: "#555555",
    marginTop: 4,
  },
  unlockSection: {
    width: "100%",
    borderRadius: 18,
    padding: 18,
    marginTop: 15,
    marginBottom: 20,
  },
  unlockHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 14,
  },
  unlockTitle: {
    fontSize: 17,
    fontWeight: "600",
    marginLeft: 10,
    letterSpacing: 0.5,
  },
  unlockItem: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
    paddingVertical: 6,
    paddingHorizontal: 10,
    backgroundColor: "rgba(255, 255, 255, 0.6)",
    borderRadius: 12,
  },
  unlockText: {
    fontSize: 15,
    color: "#444444",
    marginLeft: 10,
    fontWeight: "500",
  },
  buttonContainer: {
    width: "100%",
    paddingHorizontal: 22,
    paddingBottom: 28,
  },
  continueButton: {
    width: "100%",
    paddingVertical: 16,
    borderRadius: 30,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 6,
    alignItems: "center",
    justifyContent: "center",
  },
  continueText: {
    fontSize: 17,
    fontWeight: "bold",
    color: "#FFFFFF",
    letterSpacing: 1,
  },
  closeButton: {
    position: "absolute",
    top: 15,
    right: 15,
    width: 36,
    height: 36,
    backgroundColor: "rgba(0, 0, 0, 0.25)",
    borderRadius: 18,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10,
  },
});
