import { Dimensions, StyleSheet } from "react-native";
const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContainer: {
    width: width * 0.85,
    maxHeight: "85%", // Add max height to ensure it fits on smaller screens
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    overflow: "hidden",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#E0E0E0",
    elevation: 10,
  },
  backgroundGradient: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 120, // Reduced height to match screenshot
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
  },
  characterImage: {
    position: "absolute",
    top: 15,
    right: 20,
    width: 100,
    height: 100,
    borderRadius: 50,
    borderWidth: 2,
    borderColor: "#FFFFFF",
  },
  headerSection: {
    width: "100%",
    paddingTop: 30, // Increased padding to match the screenshot
    paddingBottom: 15,
    alignItems: "center",
    flexDirection: "row",
    paddingHorizontal: 25,
    justifyContent: "space-between",
  },
  titleContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  trophyIcon: {
    marginRight: 10,
  },
  titleText: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#FFFFFF",
    textShadowColor: "rgba(0, 0, 0, 0.2)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  xpBadge: {
    backgroundColor: "#FFFFFF",
    borderRadius: 15,
    paddingHorizontal: 12,
    paddingVertical: 6,
    flexDirection: "row",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  xpText: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#E94B8A", // Updated to pink to match screenshot
    marginLeft: 5,
  },
  contentContainer: {
    width: "100%",
    paddingHorizontal: 20,
    paddingTop: 45,
    paddingBottom: 25,
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    marginTop: -25,
  },
  rewardsSection: {
    marginTop: 10,
    paddingBottom: 15,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#333333",
    marginBottom: 15,
  },
  rewardsGrid: {
    flexDirection: "row",
    justifyContent: "space-between",
    flexWrap: "wrap",
  },
  rewardCard: {
    backgroundColor: "#F7F7F7",
    borderRadius: 15,
    padding: 15,
    width: "48%",
    alignItems: "center",
    marginBottom: 15,
    borderWidth: 1,
    borderColor: "#EEEEEE",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  rewardIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
  },
  rewardAmount: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#333333",
  },
  rewardType: {
    fontSize: 14,
    color: "#666666",
    marginTop: 2,
  },
  unlockSection: {
    width: "100%",
    backgroundColor: "#F5F5F5",
    borderRadius: 15,
    padding: 15,
    marginTop: 10,
    marginBottom: 20,
  },
  unlockHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  unlockTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333333",
    marginLeft: 10,
  },
  unlockItem: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  unlockText: {
    fontSize: 14,
    color: "#555555",
    marginLeft: 10,
  },
  unlockIcon: {
    color: "#6563FF", // Blue color for unlock icons
  },
  buttonContainer: {
    width: "100%",
    paddingHorizontal: 20,
    paddingBottom: 25,
  },
  continueButton: {
    width: "100%",
    backgroundColor: "#E94B8A", // Fixed pink color to match screenshot
    paddingVertical: 15,
    borderRadius: 30,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 4,
    alignItems: "center",
  },
  continueText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#FFFFFF",
    letterSpacing: 0.5,
  },
  closeButton: {
    position: "absolute",
    top: 15,
    right: 15,
    width: 30,
    height: 30,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10,
  },
});
